spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipes
    username: recipes
    password: recipes
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
